# fly.toml app configuration file for WhatsApp Presentation Maker
app = 'wa-presentation-maker-misty-dawn-7495'
primary_region = 'fra'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "whatsapp_data"
  destination = "/app/.wwebjs_auth"