# fly.toml app configuration file
app = "wa-presentation-maker"
primary_region = "fra"

[build]
  builder = "heroku/builder:22"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "whatsapp_data"
  destination = "/app/.wwebjs_auth"
