services:
  - type: web
    name: wa-presentation-maker
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://wa-presentation-maker.onrender.com/callback
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: PORT
        value: 8080
    disk:
      name: whatsapp-data
      mountPath: /app/.wwebjs_auth
      sizeGB: 1
